comic/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

import views


urlpatterns = patterns('',
                       url(r'^$',
                           login_required(views.ComicView.as_view(
                               template_name="comic/comic.html")), name='comic')
)

profiles/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
import views

urlpatterns = patterns('',
                       url(r'^(?P<pk>\d+)/$',
                           login_required(views.ProfileView.as_view(
                               template_name="profiles/profile/profile.html")), name='profile_detail')
)

tsune/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.http import HttpResponseRedirect

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tsune.views.home', name='home'),
    # url(r'^tsune/', include('tsune.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:go.contrib.admindocs.urls')),

    url(r'^$', lambda x: HttpResponseRedirect('/cardbox/')),  # redirect to /cardbox/
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cardbox/', include('deckglue.deckurls', namespace="deck")),
    url(r'^user/', include('authentication.urls')),
    url(r'^learning/', include('deckglue.learningurls', namespace="learning")),
    url(r'^cardbox/cards/', include('deckglue.cardurls', namespace="card")),
    url(r'^markitup/', include('markitup.urls')),
    url(r'^profile/', include('profiles.urls', namespace="profile")),
    url(r'^inplaceeditform/', include('inplaceeditform.urls')),
    url(r'^upload/', include('upload.urls', namespace="upload")),
    url(r'^comic/', include('comic.urls'))
)

upload/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
import views

urlpatterns = patterns('',
                       url(r'^$',
                           login_required(views.upload_file), name='upload')
)

tsune/templates/base.html
<!doctype html>
<html>
  {% load staticfiles %}
  <head>
    <title>{% block title %}Tsune{% endblock %}</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "tsune_base.css" %}">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static "js/get_url_param.js" %}"></script>
    <link rel="shortcut icon" href="{% static "favicon.ico" %}" />
    {% block head %}{% endblock %}
  </head>
  
  <body>
  {% block body %}
  <div class="container">
  {% block nav %}
    <nav class="navbar" role="navigation">
      <ul class="nav navbar-nav navbar-default navbar-right white-backgrd">
        {% if user.is_authenticated %}
        <li><a href="{% url 'profile:profile_detail' user.id %}" >{{  user.email }}</a></li>
        {% endif %}
        <li><a href="{% url 'deck:deck_list' %}"><span class="glyphicon glyphicon-th"></span>&nbsp;Meine Decks</a></li>
        <li>
          <a href="#" id="settingsPop"><span class="glyphicon glyphicon-cog"></span>&nbsp;Einstellungen</a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Aktionen<b class="caret"></b></a>
          <ul class="dropdown-menu">
          {% block actions %}
            <li>
              <a href="http://tsune.readthedocs.org" target="_blank">Dokumentation</a>
            </li>
            <li>
              <a href="{% url 'upload:upload' %}">Import Anki</a>
            </li>
            <li>
              <a href="{% url 'logout' %}">Logout</a>
            </li>
          {% endblock %}
          </ul>
        </li>
      </ul>
    </nav>
  {% endblock %}
      {% block content %}{% endblock %}
    </div>
  {% endblock %}
  </body>